### ISSUE TITLE
could not load: libwhisper.so

### ISSUE THREAD

**Issue by CyuHat** [maleyva1/whisper#1]
Hi, 

Thank you for this wonderful project! I was wondering if anyone was going to work on a Nim biding so this is a nice surprise.

I am still a beginner in Nim but I hope I can express my issue clearly. I am using `Linux Ubuntu 22.04.3 LTS`.

When I compile my code, I get a "could not load: libwhisper.so". So I cloned the whisper.cpp repository and created libwhisper.so with the following command: make libwhisper.so`. I then left it in the folder. But when I compile my code from the whisper.cpp folder, I still get the message that the file could not be loaded. Is the package perhaps looking for the file in a specific location?

Thanks in advance

**Comment by maleyva1** [comment]
Thank you for the kind words @CyuHat ! Lets see if I can help.

# Background
When an application is linked against a shared library, the dynamic loader looks for the given shared library on `LD_LIBRARY_PATH`. If the shared library could not be found on the `LD_LIBRARY_PATH`, you will get the error message you describe.

# Solution
The solution is relatively simple. Since you already cloned the whisper.cpp repository, I recommend to run `sudo make install` to install the shared library on your system, thus allowing the dynamic loader to find the shared library.

## Caveats
Depending on the installation path, the libraries may or may not be loaded in one of the directories specified on `LD_LIBRARY_PATH` (you can check the directories searched with the following in Bash `echo $LD_LIBRARY_PATH`). There are two solutions available if you encounter this:
1. Change the prefix (i.e. the installation directory) to point to one of the directories specified on `LD_LIBRARY_PATH`
2. Append the installation directory to `LD_LIBRARY_PATH` with `LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/path/to/library"`

**Comment by CyuHat** [comment]
Thank you very much for the quick and informative reply. It works now! 

Strangely, the `sudo make install` command returned the error "No rule for target install" (if think it is the right translation in english). But, as you mentioned, adding the shared library folder to the `LD_LIBRARY_PATH` worked.

Thanks again for this great project and your valuable time!

**Comment by upccjesse** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
jayagami, @farmprofiteth, @zsea, @TateDeng, @yasimba, @AyabongaQwabi, @Luraktinus, @Slinkydude, @feijianbagit, @ArekXD, @girishramnani, @honve, @iohaoyu, @juanmaneo, @umi, @bestplay, @cosminstn, @epitaphial, @hadi-f90, @shinyoshiaki, @r4nx, @yang24201, @dmy147, @upween, @goodleixiao, @Ltre, @viktorstrate, @wainola, @wwnje, @mzdluo123, @pyatang, @lolita1992, @v8lab, @BasixKOR, @sohelamin, @theLSA, @jaggad, @chinakook, @DiceNay, @sebaspasker, @yeshufan, @didyouseemyunicorn, @hwei-hw, @bys1123, @wqj97, @YangTakeshi, @gera2ld, @amomentunfolding, @ruankranz, @aoruoge
